-- Run once in Supabase SQL Editor
alter table public.profiles add column if not exists email text;
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('admin','manager','staff'));
create table if not exists public.categories(id bigint generated by default as identity primary key,name text not null,type text not null check(type in ('expense','income')),created_at timestamptz default now(),unique(name,type));
alter table public.categories enable row level security;
create policy "cat read" on public.categories for select to authenticated using(true);
create policy "cat manage" on public.categories for all to authenticated using(public.is_admin()) with check(public.is_admin());
grant select,insert,update,delete on public.categories to authenticated;
grant usage,select on sequence public.categories_id_seq to authenticated;
create or replace function public.is_admin() returns boolean language sql security definer set search_path=public stable as $$select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','manager'));$$;
drop policy if exists "profiles_read" on public.profiles;
create policy "profiles_read" on public.profiles for select to authenticated using(true);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email,'staff') on conflict(id) do update set email=excluded.email; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
insert into public.categories(name,type) values('Food','expense'),('Petrol','expense'),('Shopping','expense'),('Bills','expense'),('Business','expense'),('Medicine','expense'),('Transport','expense'),('Other','expense'),('Salary','income'),('Other Income','income') on conflict(name,type) do nothing;